export interface HtmlToPdfConfig {
  pageSize: 'A4' | 'A3' | 'A5' | 'Letter' | 'Legal' | 'Custom';
  customPageSize?: {
    width: number;
    height: number;
    unit: 'mm' | 'cm' | 'inch' | 'pt';
  };
  orientation: 'portrait' | 'landscape';
  margins: {
    type: 'default' | 'none' | 'small' | 'medium' | 'large' | 'custom';
    top: number;
    bottom: number;
    left: number;
    right: number;
    unit: 'mm' | 'cm' | 'inch';
  };
  printBackground: boolean;
  quality: 'standard' | 'high' | 'maximum';
  scale: number;
  enableLinks: boolean;
  executeJavaScript: boolean;
  allowExternalResources: boolean;
  headerFooter: {
    enabled: boolean;
    header: {
      leftText?: string;
      centerText?: string;
      rightText?: string;
      showDate?: boolean;
      showTitle?: boolean;
      fontSize?: number;
    };
    footer: {
      leftText?: string;
      centerText?: string;
      rightText?: string;
      showPageNumber?: boolean;
      showTotalPages?: boolean;
      showDate?: boolean;
      fontSize?: number;
    };
  };
}

export const DEFAULT_HTML_TO_PDF_CONFIG: HtmlToPdfConfig = {
  pageSize: 'A4',
  orientation: 'portrait',
  margins: {
    type: 'default',
    top: 10,
    bottom: 10,
    left: 10,
    right: 10,
    unit: 'mm',
  },
  printBackground: true,
  quality: 'high',
  scale: 1,
  enableLinks: true,
  executeJavaScript: false,
  allowExternalResources: true,
  headerFooter: {
    enabled: false,
    header: {
      leftText: '',
      centerText: '',
      rightText: '',
      showDate: false,
      showTitle: false,
      fontSize: 9,
    },
    footer: {
      leftText: 'Generated by DocFusion',
      centerText: '',
      rightText: '',
      showPageNumber: true,
      showTotalPages: true,
      showDate: false,
      fontSize: 9,
    },
  },
};

export interface HtmlConversionJob {
  id: string;
  status: 'pending' | 'processing' | 'completed' | 'failed';
  stage: 'preparing' | 'loading_css' | 'loading_assets' | 'rendering' | 'generating_pdf' | 'finalizing';
  progress: number;
  filename: string;
  pdfBuffer?: Buffer;
  downloadUrl?: string;
  pages?: number;
  size?: number;
  warnings?: string[];
  error?: string;
  createdAt: number;
}
