import { PhotoConversionConfig, PhotoConversionType } from './types';

export const PHOTO_CONVERSION_CONFIGS: Record<PhotoConversionType, PhotoConversionConfig> = {
  'jpg-to-pdf': {
    id: 'jpg-to-pdf',
    title: 'JPG → PDF',
    sourceFormat: 'JPG',
    targetFormat: 'PDF',
    sourceExts: ['.jpg', '.jpeg'],
    targetExt: '.pdf',
    acceptMime: ['image/jpeg'],
    description: 'Convert JPG images into PDF documents.',
    badgeColor: 'text-amber-400 bg-amber-500/10 border-amber-500/30',
    accentGradient: 'from-amber-600/20 to-orange-600/10 border-amber-500/40',
    iconName: 'FileText',
    allowsMultiple: true,
    hasPageOrder: true,
    supportedFeatures: [
      'Multi-image batch to single PDF document',
      'Drag-and-drop page ordering & arrangement',
      'Configurable page size: A4, US Letter, or Fit to Image',
      'Orientation and margin adjustments',
    ],
    fidelityDetails: [
      'Original pixel resolution embedded without recompression',
      'EXIF orientation auto-corrected before PDF placement',
      'Print-ready high DPI vector bounding boxes',
    ],
  },
  'pdf-to-jpg': {
    id: 'pdf-to-jpg',
    title: 'PDF → JPG',
    sourceFormat: 'PDF',
    targetFormat: 'JPG',
    sourceExts: ['.pdf'],
    targetExt: '.jpg',
    acceptMime: ['application/pdf'],
    description: 'Convert PDF pages into high-quality JPG images.',
    badgeColor: 'text-rose-400 bg-rose-500/10 border-rose-500/30',
    accentGradient: 'from-rose-600/20 to-pink-600/10 border-rose-500/40',
    iconName: 'Image',
    allowsMultiple: false,
    supportedFeatures: [
      'Crisp page rendering up to 300 DPI high-definition',
      'Convert all pages or select specific page ranges',
      'Download all pages bundled in a single ZIP or individually',
      'Adjustable JPG compression quality',
    ],
    fidelityDetails: [
      'Embedded vectors and fonts rendered at high pixel density',
      'Pure white background underlay for transparent PDF layers',
      'Accurate CMYK to RGB color space translation',
    ],
  },
  'jpg-to-png': {
    id: 'jpg-to-png',
    title: 'JPG → PNG',
    sourceFormat: 'JPG',
    targetFormat: 'PNG',
    sourceExts: ['.jpg', '.jpeg'],
    targetExt: '.png',
    acceptMime: ['image/jpeg'],
    description: 'Convert JPG images into PNG format.',
    badgeColor: 'text-blue-400 bg-blue-500/10 border-blue-500/30',
    accentGradient: 'from-blue-600/20 to-cyan-600/10 border-blue-500/40',
    iconName: 'Image',
    allowsMultiple: true,
    supportedFeatures: [
      'Lossless 24-bit PNG conversion',
      'Preserves original image dimensions and color gamut',
      'Adaptive filtering for crisp edge rendering',
      'Batch conversion with one-click zip download',
    ],
    fidelityDetails: [
      'Zero loss compression level 8',
      'Full metadata and DPI resolution preservation',
      'EXIF auto-rotation to true orientation',
    ],
  },
  'png-to-jpg': {
    id: 'png-to-jpg',
    title: 'PNG → JPG',
    sourceFormat: 'PNG',
    targetFormat: 'JPG',
    sourceExts: ['.png'],
    targetExt: '.jpg',
    acceptMime: ['image/png'],
    description: 'Convert PNG images into JPG format.',
    badgeColor: 'text-amber-400 bg-amber-500/10 border-amber-500/30',
    accentGradient: 'from-amber-600/20 to-yellow-600/10 border-amber-500/40',
    iconName: 'Image',
    allowsMultiple: true,
    supportedFeatures: [
      'MozJPEG modern encoding engine for maximum detail',
      'Customizable background color for alpha transparency flattening',
      'Fine-grained quality controls from web-optimized to 100%',
      'Batch processing for multiple transparent graphics',
    ],
    fidelityDetails: [
      'Transparency warning with white, black, or custom fill preview',
      'High-dynamic-range color preservation',
      'Resolution scaling options (Original, Small, Medium, Large)',
    ],
    disclaimer: 'JPG does not support transparency. Transparent areas will use the selected background color.',
  },
  'heic-to-jpg': {
    id: 'heic-to-jpg',
    title: 'HEIC → JPG',
    sourceFormat: 'HEIC',
    targetFormat: 'JPG',
    sourceExts: ['.heic', '.heif'],
    targetExt: '.jpg',
    acceptMime: ['image/heic', 'image/heif'],
    description: 'Convert HEIC photos into widely supported JPG images.',
    badgeColor: 'text-purple-400 bg-purple-500/10 border-purple-500/30',
    accentGradient: 'from-purple-600/20 to-indigo-600/10 border-purple-500/40',
    iconName: 'Camera',
    allowsMultiple: true,
    supportedFeatures: [
      'Full support for Apple iPhone & iPad HEIC/HEIF photos',
      'Correct EXIF orientation tag translation',
      'Retains wide-color P3 profile and camera metadata',
      'High-speed hardware-accelerated decode engine',
    ],
    fidelityDetails: [
      'Dual-engine decoding: libheif with fallback buffer parser',
      'Color tone fidelity preserved without washed-out highlights',
      'Batch conversion to universal JPEG compatible with Windows & web',
    ],
  },
  'webp-to-jpg': {
    id: 'webp-to-jpg',
    title: 'WEBP → JPG',
    sourceFormat: 'WEBP',
    targetFormat: 'JPG',
    sourceExts: ['.webp'],
    targetExt: '.jpg',
    acceptMime: ['image/webp'],
    description: 'Convert WEBP images into JPG format.',
    badgeColor: 'text-amber-400 bg-amber-500/10 border-amber-500/30',
    accentGradient: 'from-amber-600/20 to-orange-600/10 border-amber-500/40',
    iconName: 'Image',
    allowsMultiple: true,
    supportedFeatures: [
      'Convert Google WebP images to universally compatible JPG',
      'Smart background filling for transparent WebP stickers & icons',
      'High-speed batch conversion',
      'Adjustable JPEG output compression quality',
    ],
    fidelityDetails: [
      'Sharpness and high-frequency edge retention',
      'Custom background color selector for alpha channels',
      'Full metadata and resolution scale support',
    ],
  },
  'jpg-to-webp': {
    id: 'jpg-to-webp',
    title: 'JPG → WEBP',
    sourceFormat: 'JPG',
    targetFormat: 'WEBP',
    sourceExts: ['.jpg', '.jpeg'],
    targetExt: '.webp',
    acceptMime: ['image/jpeg'],
    description: 'Convert JPG images into optimized WEBP images.',
    badgeColor: 'text-teal-400 bg-teal-500/10 border-teal-500/30',
    accentGradient: 'from-teal-600/20 to-emerald-600/10 border-teal-500/40',
    iconName: 'Sparkles',
    allowsMultiple: true,
    supportedFeatures: [
      'Modern WebP format reduces file size by 30-50% with zero visible loss',
      'Advanced compression effort level 6',
      'Ideal for ultra-fast website loading & mobile apps',
      'Batch convert entire photo collections simultaneously',
    ],
    fidelityDetails: [
      'Optimized arithmetic entropy coding',
      'Subpixel chroma reconstruction',
      'Custom quality slider for maximum compression control',
    ],
  },
  'png-to-webp': {
    id: 'png-to-webp',
    title: 'PNG → WEBP',
    sourceFormat: 'PNG',
    targetFormat: 'WEBP',
    sourceExts: ['.png'],
    targetExt: '.webp',
    acceptMime: ['image/png'],
    description: 'Convert PNG images into modern WEBP format.',
    badgeColor: 'text-cyan-400 bg-cyan-500/10 border-cyan-500/30',
    accentGradient: 'from-cyan-600/20 to-blue-600/10 border-cyan-500/40',
    iconName: 'Sparkles',
    allowsMultiple: true,
    supportedFeatures: [
      'Preserves 100% full alpha transparency channels',
      'Lossless WebP option available for pixel-perfect graphics',
      'Dramatic 40-70% size reduction compared to PNG',
      'Batch conversion of UI icons, logos & transparent photos',
    ],
    fidelityDetails: [
      'Alpha quality maintained at 100% fidelity',
      'Zero color shifting or fringe artifacts along transparency borders',
      'Supports high-resolution retina graphics',
    ],
  },
  'png-to-pdf': {
    id: 'png-to-pdf',
    title: 'PNG → PDF',
    sourceFormat: 'PNG',
    targetFormat: 'PDF',
    sourceExts: ['.png'],
    targetExt: '.pdf',
    acceptMime: ['image/png'],
    description: 'Convert PNG images into PDF documents.',
    badgeColor: 'text-indigo-400 bg-indigo-500/10 border-indigo-500/30',
    accentGradient: 'from-indigo-600/20 to-purple-600/10 border-indigo-500/40',
    iconName: 'FileText',
    allowsMultiple: true,
    hasPageOrder: true,
    supportedFeatures: [
      'Embed high-resolution PNG images directly into PDF pages',
      'Full alpha transparency retained inside PDF vector containers',
      'Drag-and-drop page ordering & layout arrangement',
      'Custom page sizes: A4, Letter, or Fit to Image dimensions',
    ],
    fidelityDetails: [
      'Flate-compressed lossless image embedding',
      'Preserves crisp screenshot typography and fine lines',
      'Configurable margins and orientation (Portrait/Landscape/Auto)',
    ],
  },
  'raw-to-jpg': {
    id: 'raw-to-jpg',
    title: 'RAW → JPG',
    sourceFormat: 'RAW',
    targetFormat: 'JPG',
    sourceExts: ['.cr2', '.cr3', '.nef', '.arw', '.dng', '.raf', '.orf', '.rw2', '.raw'],
    targetExt: '.jpg',
    acceptMime: [
      'image/x-canon-cr2',
      'image/x-canon-cr3',
      'image/x-nikon-nef',
      'image/x-sony-arw',
      'image/x-adobe-dng',
      'image/x-fuji-raf',
      'image/x-olympus-orf',
      'image/x-panasonic-rw2',
      'application/octet-stream',
    ],
    description: 'Convert supported camera RAW images into JPG.',
    badgeColor: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30',
    accentGradient: 'from-emerald-600/20 to-teal-600/10 border-emerald-500/40',
    iconName: 'Camera',
    allowsMultiple: true,
    supportedFeatures: [
      'Supports Canon (.CR2, .CR3), Nikon (.NEF), Sony (.ARW), Adobe (.DNG), Fujifilm (.RAF), Olympus (.ORF), Panasonic (.RW2)',
      'Server-side RAW IFD preview extraction engine',
      'Displays camera model, lens, exposure time, aperture & ISO metadata',
      'Convert professional camera RAWs into easy-to-share JPEGs',
    ],
    fidelityDetails: [
      'Full-resolution embedded JPEG preview or direct DNG libtiff decode',
      'Extracts and displays EXIF camera & shooting parameters',
      'Adjustable JPEG output compression quality and resolution',
    ],
  },
};

export const ALL_PHOTO_CONVERSIONS = Object.values(PHOTO_CONVERSION_CONFIGS);
