import { ConversionConfig, ConversionType } from './types';

export const CONVERSION_CONFIGS: Record<ConversionType, ConversionConfig> = {
  'pdf-to-word': {
    id: 'pdf-to-word',
    title: 'PDF → Word',
    sourceFormat: 'PDF',
    targetFormat: 'Word',
    sourceExts: ['.pdf'],
    targetExt: '.docx',
    acceptMime: ['application/pdf'],
    description: 'Convert PDF documents into editable Word files.',
    badgeColor: 'text-blue-400 bg-blue-500/10 border-blue-500/30',
    accentGradient: 'from-blue-600/20 to-indigo-600/10 border-blue-500/40',
    iconName: 'FileText',
    supportedFeatures: [
      'Editable Word paragraphs & headings',
      'Preserves fonts, sizing & typography',
      'Reconstructs tabular grids into native tables',
      'Full paragraph text wrapping',
    ],
    fidelityDetails: [
      'Heading levels (H1, H2, H3) automatically classified',
      'Table borders and cell alignments reconstructed',
      'Multi-page pagination preserved with Word page breaks',
    ],
    disclaimer: 'Complex proprietary graphic layouts or scanned handwriting may convert to simplified editable text blocks.',
  },
  'pdf-to-powerpoint': {
    id: 'pdf-to-powerpoint',
    title: 'PDF → PowerPoint',
    sourceFormat: 'PDF',
    targetFormat: 'PowerPoint',
    sourceExts: ['.pdf'],
    targetExt: '.pptx',
    acceptMime: ['application/pdf'],
    description: 'Convert PDF pages into editable PowerPoint presentations.',
    badgeColor: 'text-amber-400 bg-amber-500/10 border-amber-500/30',
    accentGradient: 'from-amber-600/20 to-orange-600/10 border-amber-500/40',
    iconName: 'Presentation',
    supportedFeatures: [
      'Each PDF page converted to a 16:9 slide',
      'Preserves titles, headings & bullet points',
      'Native PowerPoint presentation shapes & tables',
      'Fully editable text boxes and slide structures',
    ],
    fidelityDetails: [
      'Presentation title automatically detected from top headings',
      'Tabular data rendered as native PowerPoint tables',
      'Standard 16:9 widescreen layout with slide counters',
    ],
    disclaimer: 'Vector clipping masks and embedded audio/video will be omitted in generated slide structures.',
  },
  'pdf-to-excel': {
    id: 'pdf-to-excel',
    title: 'PDF → Excel',
    sourceFormat: 'PDF',
    targetFormat: 'Excel',
    sourceExts: ['.pdf'],
    targetExt: '.xlsx',
    acceptMime: ['application/pdf'],
    description: 'Extract tables and structured data from PDFs into Excel.',
    badgeColor: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30',
    accentGradient: 'from-emerald-600/20 to-teal-600/10 border-emerald-500/40',
    iconName: 'Table',
    supportedFeatures: [
      'Structured table extraction into rows & columns',
      'Auto-detects numeric, currency, and date formats',
      'Multi-sheet organization by document page',
      'Styled header rows & auto-fitted column widths',
    ],
    fidelityDetails: [
      'Numbers converted to native numeric cells for formulas',
      'Separated worksheets per document page',
      'Clean table borders and alternating row styling',
    ],
    disclaimer: 'Documents without tabular alignment will have text lines mapped into organized spreadsheet rows.',
  },
  'word-to-pdf': {
    id: 'word-to-pdf',
    title: 'Word → PDF',
    sourceFormat: 'Word',
    targetFormat: 'PDF',
    sourceExts: ['.docx', '.doc'],
    targetExt: '.pdf',
    acceptMime: [
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/msword',
    ],
    description: 'Convert Word documents into PDF format.',
    badgeColor: 'text-blue-400 bg-blue-500/10 border-blue-500/30',
    accentGradient: 'from-blue-600/20 to-indigo-600/10 border-blue-500/40',
    iconName: 'FileText',
    supportedFeatures: [
      'High-resolution standard A4 PDF pages',
      'Preserves headings, paragraphs & bullet lists',
      'Reconstructs tables with clean borders',
      'Automatic page numbering & header footers',
    ],
    fidelityDetails: [
      'Formatted typography and proportional line heights',
      'Table cell backgrounds and multi-column alignment',
      'Standardized PDF/A compliant document output',
    ],
    disclaimer: 'Legacy .doc binary formats with proprietary WordArt macros will be converted into clean standardized layout.',
  },
  'powerpoint-to-pdf': {
    id: 'powerpoint-to-pdf',
    title: 'PowerPoint → PDF',
    sourceFormat: 'PowerPoint',
    targetFormat: 'PDF',
    sourceExts: ['.pptx', '.ppt'],
    targetExt: '.pdf',
    acceptMime: [
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      'application/vnd.ms-powerpoint',
    ],
    description: 'Convert PowerPoint presentations into PDF.',
    badgeColor: 'text-amber-400 bg-amber-500/10 border-amber-500/30',
    accentGradient: 'from-amber-600/20 to-orange-600/10 border-amber-500/40',
    iconName: 'Presentation',
    supportedFeatures: [
      'Widescreen 16:9 landscape PDF pages',
      'Extracts slide titles, bullet points & text content',
      'Maintains sequential presentation order',
      'High-contrast readability and slide counter badges',
    ],
    fidelityDetails: [
      'Slide numbering embedded on each page',
      'Slide layout preserved without text clipping',
      'Optimized for presenting and multi-device sharing',
    ],
    disclaimer: 'Slide animations and transitions are flattened into static PDF presentation pages.',
  },
  'excel-to-pdf': {
    id: 'excel-to-pdf',
    title: 'Excel → PDF',
    sourceFormat: 'Excel',
    targetFormat: 'PDF',
    sourceExts: ['.xlsx', '.xls'],
    targetExt: '.pdf',
    acceptMime: [
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.ms-excel',
    ],
    description: 'Convert Excel spreadsheets into PDF documents.',
    badgeColor: 'text-emerald-400 bg-emerald-500/10 border-emerald-500/30',
    accentGradient: 'from-emerald-600/20 to-teal-600/10 border-emerald-500/40',
    iconName: 'FileSpreadsheet',
    supportedFeatures: [
      'Landscape PDF layout to prevent table cutoff',
      'Sensible column scaling and cell wrapping',
      'Styled sheet headers and zebra row shading',
      'Consecutive sheet pagination with total counters',
    ],
    fidelityDetails: [
      'Grid borders and headers clearly defined',
      'Formatted values (currency, decimals, percentages) preserved',
      'Multi-sheet documents grouped with individual titles',
    ],
    disclaimer: 'Ultra-wide sheets exceeding 12 columns will wrap cleanly across subsequent pages to avoid illegible microscopic text.',
  },
};

export const ALL_CONVERSIONS = Object.values(CONVERSION_CONFIGS);
