import { HtmlToPdfConfig, PageSize } from './types';

export const DEFAULT_HTML_TO_PDF_CONFIG: HtmlToPdfConfig = {
  pageSize: 'A4',
  orientation: 'portrait',
  margins: {
    type: 'default',
    top: 10,
    bottom: 10,
    left: 10,
    right: 10,
    unit: 'mm',
  },
  printBackground: true,
  quality: 'high',
  scale: 1,
  enableLinks: true,
  executeJavaScript: false,
  allowExternalResources: true,
  headerFooter: {
    enabled: false,
    header: {
      leftText: '',
      centerText: '',
      rightText: '',
      showDate: false,
      showTitle: false,
      fontSize: 9,
    },
    footer: {
      leftText: 'Generated by DocFusion',
      centerText: '',
      rightText: '',
      showPageNumber: true,
      showTotalPages: true,
      showDate: false,
      fontSize: 9,
    },
  },
};

// Dimensions in millimeters for standard sheets
export const PAGE_DIMENSIONS_MM: Record<PageSize, { width: number; height: number }> = {
  A4: { width: 210, height: 297 },
  A3: { width: 297, height: 420 },
  A5: { width: 148, height: 210 },
  Letter: { width: 215.9, height: 279.4 },
  Legal: { width: 215.9, height: 355.6 },
  Custom: { width: 210, height: 297 },
};

export const MARGIN_PRESETS: Record<string, { top: number; bottom: number; left: number; right: number }> = {
  default: { top: 10, bottom: 10, left: 10, right: 10 },
  none: { top: 0, bottom: 0, left: 0, right: 0 },
  small: { top: 5, bottom: 5, left: 5, right: 5 },
  medium: { top: 15, bottom: 15, left: 15, right: 15 },
  large: { top: 25, bottom: 25, left: 25, right: 25 },
};
