import React from 'react';
import { Layout, Calendar, Hash, Type } from 'lucide-react';
import { HeaderFooterConfig } from './types';

interface HeaderFooterSettingsProps {
  config: HeaderFooterConfig;
  onChange: (cfg: HeaderFooterConfig) => void;
  disabled?: boolean;
}

export const HeaderFooterSettings: React.FC<HeaderFooterSettingsProps> = ({
  config,
  onChange,
  disabled = false,
}) => {
  const update = (patch: Partial<HeaderFooterConfig>) => {
    onChange({ ...config, ...patch });
  };

  const updateHeader = (patch: Partial<HeaderFooterConfig['header']>) => {
    onChange({
      ...config,
      header: { ...config.header, ...patch },
    });
  };

  const updateFooter = (patch: Partial<HeaderFooterConfig['footer']>) => {
    onChange({
      ...config,
      footer: { ...config.footer, ...patch },
    });
  };

  return (
    <div className="bg-[#121220] border border-[#24243a] rounded-3xl p-5 sm:p-6 space-y-5">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2 text-xs font-mono uppercase tracking-wider text-[#a78bfa]">
          <Layout className="w-3.5 h-3.5" />
          <span>Page Header &amp; Footer</span>
        </div>

        <label className="flex items-center gap-2 cursor-pointer">
          <span className="text-xs text-neutral-300 font-semibold">Enable</span>
          <input
            type="checkbox"
            checked={config.enabled}
            onChange={(e) => update({ enabled: e.target.checked })}
            disabled={disabled}
            className="w-4 h-4 accent-[#7c3aed] rounded cursor-pointer"
          />
        </label>
      </div>

      {config.enabled && (
        <div className="space-y-5 pt-2">
          {/* Header Controls */}
          <div className="space-y-2.5">
            <h4 className="text-xs font-bold text-white uppercase tracking-wider">
              Document Header
            </h4>
            <div className="space-y-2 text-xs">
              <div>
                <span className="text-[10px] text-neutral-500 block mb-1">Left Header Text</span>
                <input
                  type="text"
                  placeholder="e.g. My Company Inc."
                  value={config.header.leftText}
                  onChange={(e) => updateHeader({ leftText: e.target.value })}
                  disabled={disabled}
                  className="w-full bg-[#18182a] border border-[#2b2b42] rounded-lg px-2.5 py-1.5 text-white placeholder:text-neutral-600 focus:outline-none focus:border-[#7c3aed]"
                />
              </div>

              <div>
                <span className="text-[10px] text-neutral-500 block mb-1">Center Title</span>
                <input
                  type="text"
                  placeholder="e.g. Confidential Report"
                  value={config.header.centerText}
                  onChange={(e) => updateHeader({ centerText: e.target.value })}
                  disabled={disabled}
                  className="w-full bg-[#18182a] border border-[#2b2b42] rounded-lg px-2.5 py-1.5 text-white placeholder:text-neutral-600 focus:outline-none focus:border-[#7c3aed]"
                />
              </div>

              <div className="flex items-center justify-between pt-1">
                <label className="flex items-center gap-2 text-xs text-neutral-400 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={config.header.showDate}
                    onChange={(e) => updateHeader({ showDate: e.target.checked })}
                    disabled={disabled}
                    className="accent-[#7c3aed] rounded"
                  />
                  <span>Show Current Date (Right)</span>
                </label>
              </div>
            </div>
          </div>

          {/* Footer Controls */}
          <div className="space-y-2.5 pt-3 border-t border-[#222234]">
            <h4 className="text-xs font-bold text-white uppercase tracking-wider">
              Document Footer
            </h4>
            <div className="space-y-2 text-xs">
              <div>
                <span className="text-[10px] text-neutral-500 block mb-1">Left Footer Text</span>
                <input
                  type="text"
                  placeholder="e.g. Generated by DocFusion"
                  value={config.footer.leftText}
                  onChange={(e) => updateFooter({ leftText: e.target.value })}
                  disabled={disabled}
                  className="w-full bg-[#18182a] border border-[#2b2b42] rounded-lg px-2.5 py-1.5 text-white placeholder:text-neutral-600 focus:outline-none focus:border-[#7c3aed]"
                />
              </div>

              <div className="flex flex-wrap items-center gap-4 pt-1">
                <label className="flex items-center gap-2 text-xs text-neutral-400 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={config.footer.showPageNumber}
                    onChange={(e) => updateFooter({ showPageNumber: e.target.checked })}
                    disabled={disabled}
                    className="accent-[#7c3aed] rounded"
                  />
                  <span>Page Number</span>
                </label>

                <label className="flex items-center gap-2 text-xs text-neutral-400 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={config.footer.showTotalPages}
                    onChange={(e) => updateFooter({ showTotalPages: e.target.checked })}
                    disabled={disabled}
                    className="accent-[#7c3aed] rounded"
                  />
                  <span>Total Pages ("Page 1 of 5")</span>
                </label>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
