import { ResizePreset } from './types';

export const RESIZE_PRESETS: ResizePreset[] = [
  // Social Media Presets
  {
    id: 'ig-square',
    category: 'social',
    name: 'Instagram Square',
    width: 1080,
    height: 1080,
    ratio: '1:1',
    description: 'Standard Instagram feed square post',
  },
  {
    id: 'ig-portrait',
    category: 'social',
    name: 'Instagram Portrait',
    width: 1080,
    height: 1350,
    ratio: '4:5',
    description: 'Max vertical feed image for high engagement',
  },
  {
    id: 'ig-story',
    category: 'social',
    name: 'Instagram Story / Reel',
    width: 1080,
    height: 1920,
    ratio: '9:16',
    description: 'Full vertical mobile screen (Story, Reel, TikTok)',
  },
  {
    id: 'fb-cover',
    category: 'social',
    name: 'Facebook Cover',
    width: 820,
    height: 312,
    ratio: '16:9',
    description: 'Optimized desktop and mobile profile banner',
  },
  {
    id: 'twitter-post',
    category: 'social',
    name: 'X (Twitter) Post',
    width: 1200,
    height: 675,
    ratio: '16:9',
    description: 'Crisp timeline feed image card',
  },
  {
    id: 'linkedin-banner',
    category: 'social',
    name: 'LinkedIn Cover Banner',
    width: 1584,
    height: 396,
    ratio: '4:1',
    description: 'Professional personal profile background banner',
  },
  {
    id: 'yt-thumb',
    category: 'social',
    name: 'YouTube Thumbnail',
    width: 1280,
    height: 720,
    ratio: '16:9',
    description: 'Standard high-definition video thumbnail',
  },

  // Profile Photos
  {
    id: 'profile-lg',
    category: 'profile',
    name: 'High-Res Avatar',
    width: 800,
    height: 800,
    ratio: '1:1',
    description: 'Universal high-resolution square avatar',
  },
  {
    id: 'profile-md',
    category: 'profile',
    name: 'Standard Profile Photo',
    width: 500,
    height: 500,
    ratio: '1:1',
    description: 'Ideal for WhatsApp, Slack, Teams, and Google',
  },
  {
    id: 'profile-sm',
    category: 'profile',
    name: 'Compact Avatar',
    width: 300,
    height: 300,
    ratio: '1:1',
    description: 'Lightweight web profile icon',
  },
  {
    id: 'discord-avatar',
    category: 'profile',
    name: 'Discord Avatar',
    width: 128,
    height: 128,
    ratio: '1:1',
    description: 'Small square avatar with instant load',
  },

  // Documents & Print
  {
    id: 'doc-passport',
    category: 'document',
    name: 'Passport Photo (2x2")',
    width: 600,
    height: 600,
    ratio: '1:1',
    description: 'Official biometric passport & visa digital specification (300 DPI)',
  },
  {
    id: 'doc-id-card',
    category: 'document',
    name: 'ID Card (CR80)',
    width: 856,
    height: 540,
    ratio: '1.58:1',
    description: 'Standard driver license & badge dimensions',
  },
  {
    id: 'doc-a4',
    category: 'document',
    name: 'A4 Sheet Print (300 DPI)',
    width: 2480,
    height: 3508,
    ratio: '1:1.41',
    description: 'Ultra high-definition international paper print',
  },
  {
    id: 'doc-us-letter',
    category: 'document',
    name: 'US Letter Print (300 DPI)',
    width: 2550,
    height: 3300,
    ratio: '1:1.29',
    description: 'Standard North American document print resolution',
  },
  {
    id: 'doc-photo-4x6',
    category: 'document',
    name: '4x6" Photo Print',
    width: 1800,
    height: 1200,
    ratio: '3:2',
    description: 'Lab photo print standard at 300 DPI',
  },

  // Web & Displays
  {
    id: 'web-4k',
    category: 'web',
    name: '4K Ultra HD',
    width: 3840,
    height: 2160,
    ratio: '16:9',
    description: 'Maximum resolution wallpaper & presentation display',
  },
  {
    id: 'web-2k',
    category: 'web',
    name: '2K QHD',
    width: 2560,
    height: 1440,
    ratio: '16:9',
    description: 'Standard high-end desktop monitor resolution',
  },
  {
    id: 'web-fhd',
    category: 'web',
    name: 'Full HD (1080p)',
    width: 1920,
    height: 1080,
    ratio: '16:9',
    description: 'Most popular desktop & web video resolution',
  },
  {
    id: 'web-hd',
    category: 'web',
    name: 'HD (720p)',
    width: 1280,
    height: 720,
    ratio: '16:9',
    description: 'Fast loading web banner & featured hero',
  },
  {
    id: 'web-blog-thumb',
    category: 'web',
    name: 'Blog Thumbnail',
    width: 800,
    height: 600,
    ratio: '4:3',
    description: 'Compact blog post & card grid image',
  },
  {
    id: 'web-mobile-card',
    category: 'web',
    name: 'Mobile Card',
    width: 640,
    height: 480,
    ratio: '4:3',
    description: 'Bandwidth-friendly mobile thumbnail',
  },
];
